name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Prisma Generate
        run: pnpm prisma:generate

      - name: Run Build
        run: pnpm build

      - name: Run Unit Tests
        run: pnpm test

      - name: Lint Codebase
        run: pnpm lint

      - name: Check Code Formatting
        run: pnpm format:check
